#!/bin/bash

# Containers without Containers  <mark.griffin@linux.com>
# https://github.com/nerdgeneration/containerless

set -e

# We'll be using a union filesystem, EPEL has an implementation
yum install --assumeyes epel-release
yum install --assumeyes funionfs

# Install CentOS 6 functions
cp centos6/functions /usr/local/bin/container-functions
