#!/bin/bash

# Containers without Containers  <mark.griffin@linux.com>
# https://github.com/nerdgeneration/containerless

set -e

# CentOS version dependent stuff lives in a library
source /usr/local/bin/container-functions

cnt_name="$1"
cnt_deploy_name="$2"
cnt_action="$3"

if [[ "$cnt_action" == "on" ]]; then
	cnt_deploy "$cnt_name" "$cnt_deploy_name"

elif [[ "$cnt_action" == "off" ]]; then
	cnt_undeploy "$cnt_name" "$cnt_deploy_name"

else
    echo "Syntax: container-deploy container-name deployed-name on|off" >&2
fi
